### ISSUE TITLE
Update the Hex repo with latest changes

### ISSUE THREAD

**Issue by walterbm** [werbitzky/elastix#37]
Currently the version of `elastix` on Hex is `0.4.0`. That version seems to be missing some of the recent updates (most notably support for custom headers). Is it possible to update the hex repo to the new version that includes recent changes?

Also, I noticed all documentation seems to be missing from the Hex docs page. Is adding documentation open and feasible for new contributors?

**Comment by JoshSmith** [comment]
Hey @werbitzky just wanted to check in on this.

**Comment by werbitzky** [comment]
Hi, I've updated the Hex repo to v0.5.0 to include the latest contributions. One test is failing probably due to an Elasticsearch version change – locally the tests are running through, I'll follow up with a minor update for travis.

Docs are encouraged @walterbm, I messed up with version v0.4.0 and introduced a broken link. (v0.3.2 has a working hexdocs link)

Cheers

**Comment by JoshSmith** [comment]
Thanks @werbitzky!
